exp_arguments:    
  save_exp_code:    HEATMAP_OUTPUT                                                      # name tag for saving generated figures and assets
  raw_save_dir:     results/demo_TCGABRCA_4Heatmaps_20x_t0f0                            # where to save raw asset files
  batch_size:       500


patching_arguments:                                                                     # arguments for patching
  patch_size:       [256, 256]                                                          # target size 
  overlap:          0.1                                                                 # heatmap overlapping rate
  patch_level:      0                                                                   # level to extract patches   
  custom_downsample: 2                                                                  # custom downsample factor for patching


data_arguments: 
  preset:                                                                               # preset csv file for segmentation/patching
  process_list:                                                                         # [first priority] csv list containing slide_ids (can additionally have seg/patch paramters, class labels, etc.) 
  data_dir:         demo-data/                                                          # [second priority], where is slide data stored; can be a single str path or a list of subdir
  spec_slide:                                                                           # [third priority], list of slide_ids to process
  slide_ext:        .svs                                                                # file extention for slides
  data_csv_info:                                                                        # the csv file containing the `slide id` and `label` [commonly None.]
  label_dict:       {"Low": 1, "High": 0}                                               # label dictionary for str: interger mapping (optional)

  data_dir_key:     source                                                              # column name for key in data_dir (if a dict mapping is used)


model_arguments:                                                                      
  ckpt_path:        CPMP_model_weights/CPMP_t0f0_checkpoint_v1.pt                       # arguments for initializing model from checkpoint
  model_type:       CPMP                                                                # model type
  model_size:       uni1024                                                             # size of model
  encoding_dim:     1024                                                                # patch encoding dim
  n_classes:        1                                                                   # number of classes
  drop_out:         0.5                                                                 # a float num, enable dropout (p=0.5)
  agent_token_num:  1                                                                   # the number of agent tokens in CPMP, (default: 1)
  tile_model:       uni                                                                 # pretrained model for tile encoding

  discard_ratio:    0.75
  best_thresh:      0.571
  gpu:              0


heatmap_arguments:
  vis_level:        2                                                                   # downsample at which to visualize heatmap (-1 refers to downsample closest to 32x downsample)
  alpha:            0.25                                                                # transparency for overlaying heatmap on background (0: background only, 1: foreground only)
  blank_canvas:     false                                                               # whether to use a blank canvas instead of original slide
  save_orig:        false                                                               # whether to also save the original H&E image
  save_ext:         png                                                                 # file extension for saving heatmap/original image
  use_ref_scores:   false                                                               # whether to calculate percentile scores in reference to the set of non-overlapping patches
  blur:             true                                                                # whether to use gaussian blur for further smoothing
  use_center_shift: true                                                                # whether to shift the 4 default corner points for checking if a patch is inside a foreground contour
  use_roi:          false                                                               # whether to only compute heatmap for ROI specified by x1, x2, y1, y2
  calc_heatmap:     true                                                                # whether to calculate heatmap with specified overlap (by default, coarse heatmap without overlap is always calculated)
  binarize:         false                                                               # whether to binarize attention scores
  binary_thresh:    -1                                                                  # binarization threshold: (0, 1)
  cmap:             rainbow                                                             # jet


sample_arguments:
  samples:
    - name: "topk_high_attention"
      sample: true
      seed: 1
      k: 100 # save top-k patches
      mode: topk